name: WorldPlayersLimit
main: onl.fdt.java.minecraft.bukkit.WorldPlayersLimit.Main
version: 0.0.3
author: FredericDT
permissions:
  worldplayerslimit.admin:
    default: op
commands:
  worldplayerslimit:
    permission: randomsummonsquid.admin